package catalog

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"slices"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/Silo-Server/silo-server/internal/collectionutil"
	"github.com/Silo-Server/silo-server/internal/idgen"
	"github.com/Silo-Server/silo-server/internal/models"
	"github.com/Silo-Server/silo-server/internal/requestlock"
)

var ErrLibraryCollectionNotFound = errors.New("library collection not found")

type CreateLibraryCollectionInput struct {
	LibraryID           int
	LibraryIDs          []int
	Slug                string
	Title               string
	Description         string
	CollectionType      string
	Visibility          string
	SortOrder           int
	GroupID             *string
	Featured            bool
	PosterURL           string
	BackdropURL         string
	PosterThumbhash     string
	BackdropThumbhash   string
	PosterAutoGenerated bool
	PosterFromTemplate  bool
	SourceURL           string
	QueryDefinition     json.RawMessage
	SortConfig          json.RawMessage
	SourceConfig        json.RawMessage
	ManagementMode      string
	ManagementSource    string
	ManagementKey       string
	SyncSchedule        *string
}

type UpdateLibraryCollectionInput struct {
	ExpectedRevision    *int64
	ID                  string
	LibraryIDs          *[]int
	Slug                *string
	Title               *string
	Description         *string
	CollectionType      *string
	Visibility          *string
	SortOrder           *int
	SetGroupID          **string
	Featured            *bool
	PosterURL           *string
	BackdropURL         *string
	PosterThumbhash     *string
	BackdropThumbhash   *string
	PosterAutoGenerated *bool
	PosterFromTemplate  *bool
	SourceURL           *string
	QueryDefinition     json.RawMessage
	SortConfig          json.RawMessage
	SourceConfig        json.RawMessage
	ManagementMode      *string
	ManagementSource    *string
	ManagementKey       *string
	SyncSchedule        *string
	NextSyncAt          *time.Time
}

type ListLibraryCollectionsOptions struct {
	IncludeHidden bool
}

type LibraryCollectionItemInput struct {
	MediaItemID string
	Position    int
	SourceRank  int
}

type RecordLibraryCollectionSyncRunInput struct {
	CollectionID   string
	Status         string
	Message        string
	ItemsAdded     int
	ItemsRemoved   int
	ItemsMatched   int
	ItemsUnmatched int
	Warnings       json.RawMessage
	StartedAt      time.Time
	CompletedAt    time.Time
}

type LibraryCollectionRepository struct {
	pool *pgxpool.Pool
}

func NewLibraryCollectionRepository(pool *pgxpool.Pool) *LibraryCollectionRepository {
	return &LibraryCollectionRepository{pool: pool}
}

// HasItem reports whether an item is currently a member of a collection.
// Admin repair actions use this to remain scoped to the collection that owns
// the virtual materialization request.
func (r *LibraryCollectionRepository) HasItem(ctx context.Context, collectionID, itemID string) (bool, error) {
	if r == nil || r.pool == nil {
		return false, errors.New("library collection repository is not configured")
	}
	var exists bool
	if err := r.pool.QueryRow(ctx, `
		SELECT EXISTS(SELECT 1 FROM library_collection_items
		              WHERE collection_id=$1 AND media_item_id=$2)`, collectionID, itemID).Scan(&exists); err != nil {
		return false, fmt.Errorf("check collection item membership: %w", err)
	}
	return exists, nil
}

// TouchCollectionItem updates the updated_at timestamp of a collection membership row.
// This is used by reconciliation to advance round-robin progress across batches and
// prevent failing items from starving later eligible items.
func (r *LibraryCollectionRepository) TouchCollectionItem(ctx context.Context, collectionID, itemID string) error {
	if r == nil || r.pool == nil {
		return errors.New("library collection repository is not configured")
	}
	_, err := r.pool.Exec(ctx, `
		UPDATE library_collection_items
		SET updated_at = NOW()
		WHERE collection_id = $1 AND media_item_id = $2`, collectionID, itemID)
	if err != nil {
		return fmt.Errorf("touch collection item: %w", err)
	}
	return nil
}

const libraryCollectionColumns = `lc.id, lc.library_id, lc.slug, lc.title, lc.description,
	lc.collection_type, lc.visibility, COALESCE(scope_lcl.sort_order, lc.sort_order), scope_lcl.group_id, lc.featured, lc.poster_url,
	lc.backdrop_url, lc.poster_thumbhash, lc.backdrop_thumbhash, lc.poster_auto_generated, lc.poster_from_template,
	lc.source_url, lc.query_definition, lc.sort_config, lc.source_config,
	lc.management_mode, lc.management_source, lc.management_key, lc.last_sync_status,
	lc.last_sync_message, lc.last_sync_at, lc.sync_schedule, lc.next_sync_at,
	CASE WHEN lc.collection_type = 'smart' THEN lc.item_count_cached
	     ELSE COALESCE(COUNT(DISTINCT lci.media_item_id), 0) END,
	lc.created_at, lc.updated_at,
	COALESCE(ARRAY_AGG(DISTINCT lcl.library_id) FILTER (WHERE lcl.library_id IS NOT NULL), ARRAY[]::integer[])`

const libraryCollectionScopeFallbackJoin = `LEFT JOIN LATERAL (
	SELECT group_id, sort_order
	FROM library_collection_libraries
	WHERE collection_id = lc.id
	ORDER BY (group_id IS NULL) ASC, updated_at DESC, library_id ASC
	LIMIT 1
) scope_lcl ON true`

func scanLibraryCollection(row pgx.Row) (*models.LibraryCollection, error) {
	var collection models.LibraryCollection
	var libraryIDs []int32
	err := row.Scan(
		&collection.ID,
		&collection.LibraryID,
		&collection.Slug,
		&collection.Title,
		&collection.Description,
		&collection.CollectionType,
		&collection.Visibility,
		&collection.SortOrder,
		&collection.GroupID,
		&collection.Featured,
		&collection.PosterURL,
		&collection.BackdropURL,
		&collection.PosterThumbhash,
		&collection.BackdropThumbhash,
		&collection.PosterAutoGenerated,
		&collection.PosterFromTemplate,
		&collection.SourceURL,
		&collection.QueryDefinition,
		&collection.SortConfig,
		&collection.SourceConfig,
		&collection.ManagementMode,
		&collection.ManagementSource,
		&collection.ManagementKey,
		&collection.LastSyncStatus,
		&collection.LastSyncMessage,
		&collection.LastSyncAt,
		&collection.SyncSchedule,
		&collection.NextSyncAt,
		&collection.ItemCount,
		&collection.CreatedAt,
		&collection.UpdatedAt,
		&libraryIDs,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrLibraryCollectionNotFound
		}
		return nil, fmt.Errorf("scanning library collection: %w", err)
	}
	collection.LibraryIDs = int32SliceToInts(libraryIDs)
	if len(collection.LibraryIDs) == 0 && collection.LibraryID > 0 {
		collection.LibraryIDs = []int{collection.LibraryID}
	}
	return &collection, nil
}

func scanLibraryCollections(rows pgx.Rows) ([]*models.LibraryCollection, error) {
	var collections []*models.LibraryCollection
	for rows.Next() {
		collection, err := scanLibraryCollection(rows)
		if err != nil {
			return nil, err
		}
		collections = append(collections, collection)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating library collections: %w", err)
	}
	return collections, nil
}

func (r *LibraryCollectionRepository) Create(ctx context.Context, input CreateLibraryCollectionInput) (*models.LibraryCollection, error) {
	input.LibraryIDs = normalizeCollectionLibraryIDs(input.LibraryID, input.LibraryIDs)
	if len(input.SourceConfig) == 0 {
		input.SourceConfig = json.RawMessage(`{}`)
	}
	if len(input.QueryDefinition) == 0 {
		input.QueryDefinition = json.RawMessage(`{}`)
	}
	if len(input.SortConfig) == 0 {
		input.SortConfig = json.RawMessage(`{}`)
	}
	if input.Visibility == "" {
		input.Visibility = LibraryCollectionVisibilityVisible
	}
	if input.CollectionType == "" {
		input.CollectionType = libraryCollectionTypeManual
	}
	if input.ManagementMode == "" {
		input.ManagementMode = "manual"
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("beginning library collection create: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	query := `
		INSERT INTO library_collections (
			id, library_id, slug, title, description, collection_type, visibility,
			sort_order, group_label, featured, poster_url, backdrop_url,
			poster_thumbhash, backdrop_thumbhash, poster_auto_generated, poster_from_template,
			source_url, query_definition, sort_config, source_config,
			management_mode, management_source, management_key,
			sync_schedule, next_sync_at
		) VALUES (
			$1, $2, $3, $4, $5, $6, $7,
			$8, '', $9, $10, $11,
			$12, $13, $14, $15,
			$16, $17, $18, $19,
			$20, $21, $22,
			$23, $24
		)
		RETURNING id`

	id, err := idgen.NextID()
	if err != nil {
		return nil, fmt.Errorf("generate id: %w", err)
	}
	legacyLibraryID := input.LibraryID
	if legacyLibraryID <= 0 && len(input.LibraryIDs) > 0 {
		legacyLibraryID = input.LibraryIDs[0]
	}

	if err := tx.QueryRow(
		ctx,
		query,
		id,
		legacyLibraryID,
		input.Slug,
		input.Title,
		input.Description,
		input.CollectionType,
		input.Visibility,
		input.SortOrder,
		input.Featured,
		input.PosterURL,
		input.BackdropURL,
		input.PosterThumbhash,
		input.BackdropThumbhash,
		input.PosterAutoGenerated,
		input.PosterFromTemplate,
		input.SourceURL,
		input.QueryDefinition,
		input.SortConfig,
		input.SourceConfig,
		input.ManagementMode,
		input.ManagementSource,
		input.ManagementKey,
		input.SyncSchedule,
		computeNextSyncAt(input.SyncSchedule),
	).Scan(&id); err != nil {
		return nil, fmt.Errorf("creating library collection: %w", err)
	}

	var groupLibraryID *int
	if input.GroupID != nil {
		var (
			libraryID int
			kind      models.LibraryCollectionGroupKind
		)
		if err := tx.QueryRow(ctx, `
			SELECT library_id, kind
			FROM library_collection_groups
			WHERE id = $1
		`, *input.GroupID).Scan(&libraryID, &kind); err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return nil, ErrLibraryCollectionGroupNotFound
			}
			return nil, fmt.Errorf("loading collection group: %w", err)
		}
		if kind == models.GroupKindUserCollections {
			return nil, fmt.Errorf("user-collections group cannot accept admin collections")
		}
		groupLibraryID = &libraryID
	}

	if err := lockLibraryCollectionOrderRevisions(ctx, tx, input.LibraryIDs); err != nil {
		return nil, err
	}

	groupMatchedLibrary := input.GroupID == nil
	for _, libraryID := range input.LibraryIDs {
		var membershipGroupID *string
		if groupLibraryID != nil && libraryID == *groupLibraryID {
			membershipGroupID = input.GroupID
			groupMatchedLibrary = true
		}
		if _, err := tx.Exec(ctx, `
			INSERT INTO library_collection_libraries (collection_id, library_id, group_id, sort_order)
			SELECT $1, $2, $3,
			       COALESCE((
			           SELECT MAX(sort_order) + 1
			           FROM library_collection_libraries
			           WHERE library_id = $2
			             AND group_id IS NOT DISTINCT FROM $3
			       ), 0)
			ON CONFLICT (collection_id, library_id) DO NOTHING
		`, id, libraryID, membershipGroupID); err != nil {
			return nil, fmt.Errorf("creating collection library scope: %w", err)
		}
	}
	if !groupMatchedLibrary {
		return nil, fmt.Errorf("collection group library is not included in collection scope")
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("committing library collection create: %w", err)
	}

	return r.GetByID(ctx, id)
}

func (r *LibraryCollectionRepository) GetByID(ctx context.Context, id string) (*models.LibraryCollection, error) {
	query := fmt.Sprintf(`
		SELECT %s
		FROM library_collections lc
		%s
		LEFT JOIN library_collection_items lci ON lci.collection_id = lc.id
		LEFT JOIN library_collection_libraries lcl ON lcl.collection_id = lc.id
		WHERE lc.id = $1
		GROUP BY lc.id, scope_lcl.group_id, scope_lcl.sort_order
	`, libraryCollectionColumns, libraryCollectionScopeFallbackJoin)

	return scanLibraryCollection(r.pool.QueryRow(ctx, query, id))
}

// GetByManagementKey returns the collection that owns the given management
// key within the supplied mode/source pair. Scoping by mode and source guards
// against future mode collisions on the unique-key index returning a
// surface-owned collection to a caller from a different surface.
func (r *LibraryCollectionRepository) GetByManagementKey(ctx context.Context, mode, source, key string) (*models.LibraryCollection, error) {
	query := fmt.Sprintf(`
		SELECT %s
		FROM library_collections lc
		%s
		LEFT JOIN library_collection_items lci ON lci.collection_id = lc.id
		LEFT JOIN library_collection_libraries lcl ON lcl.collection_id = lc.id
		WHERE lc.management_mode = $1
		  AND lc.management_source = $2
		  AND lc.management_key = $3
		GROUP BY lc.id, scope_lcl.group_id, scope_lcl.sort_order
	`, libraryCollectionColumns, libraryCollectionScopeFallbackJoin)

	return scanLibraryCollection(r.pool.QueryRow(ctx, query, mode, source, key))
}

func (r *LibraryCollectionRepository) ListByLibrary(ctx context.Context, libraryID int, opts ListLibraryCollectionsOptions) ([]*models.LibraryCollection, error) {
	return r.ListAll(ctx, &libraryID, opts)
}

func (r *LibraryCollectionRepository) ListAll(ctx context.Context, libraryID *int, opts ListLibraryCollectionsOptions) ([]*models.LibraryCollection, error) {
	var (
		conditions []string
		args       []any
		scopeJoin  string
	)
	argIdx := 1
	if libraryID != nil {
		scopeJoin = fmt.Sprintf(`JOIN library_collection_libraries scope_lcl
			ON scope_lcl.collection_id = lc.id AND scope_lcl.library_id = $%d`, argIdx)
		args = append(args, *libraryID)
	} else {
		scopeJoin = libraryCollectionScopeFallbackJoin
	}
	if !opts.IncludeHidden {
		conditions = append(conditions, "lc.visibility = 'visible'")
	}
	if len(conditions) == 0 {
		conditions = append(conditions, "1 = 1")
	}

	query := fmt.Sprintf(`
		SELECT %s
		FROM library_collections lc
		%s
		LEFT JOIN library_collection_items lci ON lci.collection_id = lc.id
		LEFT JOIN library_collection_libraries lcl ON lcl.collection_id = lc.id
		WHERE %s
		GROUP BY lc.id, scope_lcl.group_id, scope_lcl.sort_order
		ORDER BY lc.featured DESC, COALESCE(scope_lcl.sort_order, lc.sort_order) ASC, lc.title ASC
	`, libraryCollectionColumns, scopeJoin, strings.Join(conditions, " AND "))

	rows, err := r.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("listing library collections: %w", err)
	}
	defer rows.Close()

	return scanLibraryCollections(rows)
}

// ListContainingItem returns the visible collections that store a membership
// row for mediaItemID, ordered by title. The membership subquery is served by
// the library_collection_items media_item_id index. Smart (live-query)
// collections derive their members at read time and store no rows, so they are
// not reported.
func (r *LibraryCollectionRepository) ListContainingItem(ctx context.Context, mediaItemID string) ([]*models.LibraryCollection, error) {
	query := fmt.Sprintf(`
		SELECT %s
		FROM library_collections lc
		%s
		LEFT JOIN library_collection_items lci ON lci.collection_id = lc.id
		LEFT JOIN library_collection_libraries lcl ON lcl.collection_id = lc.id
		WHERE lc.visibility = 'visible'
		  AND lc.id IN (
			SELECT member.collection_id
			FROM library_collection_items member
			WHERE member.media_item_id = $1
		  )
		GROUP BY lc.id, scope_lcl.group_id, scope_lcl.sort_order
		ORDER BY lower(lc.title) ASC, lc.title ASC, lc.id ASC
	`, libraryCollectionColumns, libraryCollectionScopeFallbackJoin)

	rows, err := r.pool.Query(ctx, query, mediaItemID)
	if err != nil {
		return nil, fmt.Errorf("listing collections containing item: %w", err)
	}
	defer rows.Close()

	return scanLibraryCollections(rows)
}

// AnyVisibleInLibraries reports whether at least one visible library collection
// is scoped to any of the given libraries. It mirrors the visibility rules of
// ListAll + the compat layer's collectionVisible (multi-library scope rows, or
// the legacy single library_id column when a collection has no scope rows) but
// is an index-only EXISTS probe: no item join, no aggregation, no row build. It
// short-circuits the first match, so it stays cheap enough to run on every
// /UserViews request to gate the synthetic "Collections" view.
func (r *LibraryCollectionRepository) AnyVisibleInLibraries(ctx context.Context, libraryIDs []int) (bool, error) {
	if len(libraryIDs) == 0 {
		return false, nil
	}
	const query = `SELECT EXISTS (
		SELECT 1
		FROM library_collections lc
		WHERE lc.visibility = 'visible'
		  AND (
			EXISTS (
				SELECT 1 FROM library_collection_libraries lcl
				WHERE lcl.collection_id = lc.id AND lcl.library_id = ANY($1)
			)
			OR (
				NOT EXISTS (SELECT 1 FROM library_collection_libraries lcl WHERE lcl.collection_id = lc.id)
				AND lc.library_id = ANY($1)
			)
		  )
	)`
	var exists bool
	if err := r.pool.QueryRow(ctx, query, libraryIDs).Scan(&exists); err != nil {
		return false, fmt.Errorf("checking for visible library collections: %w", err)
	}
	return exists, nil
}

func (r *LibraryCollectionRepository) Update(ctx context.Context, input UpdateLibraryCollectionInput) error {
	var (
		sets []string
		args []any
	)
	argIdx := 1

	if input.Slug != nil {
		sets = append(sets, fmt.Sprintf("slug = $%d", argIdx))
		args = append(args, *input.Slug)
		argIdx++
	}
	if input.Title != nil {
		sets = append(sets, fmt.Sprintf("title = $%d", argIdx))
		args = append(args, *input.Title)
		argIdx++
	}
	if input.Description != nil {
		sets = append(sets, fmt.Sprintf("description = $%d", argIdx))
		args = append(args, *input.Description)
		argIdx++
	}
	if input.CollectionType != nil {
		sets = append(sets, fmt.Sprintf("collection_type = $%d", argIdx))
		args = append(args, *input.CollectionType)
		argIdx++
	}
	if input.Visibility != nil {
		sets = append(sets, fmt.Sprintf("visibility = $%d", argIdx))
		args = append(args, *input.Visibility)
		argIdx++
	}
	if input.SortOrder != nil {
		sets = append(sets, fmt.Sprintf("sort_order = $%d", argIdx))
		args = append(args, *input.SortOrder)
		argIdx++
	}
	if input.Featured != nil {
		sets = append(sets, fmt.Sprintf("featured = $%d", argIdx))
		args = append(args, *input.Featured)
		argIdx++
	}
	if input.PosterURL != nil {
		sets = append(sets, fmt.Sprintf("poster_url = $%d", argIdx))
		args = append(args, *input.PosterURL)
		argIdx++
	}
	if input.BackdropURL != nil {
		sets = append(sets, fmt.Sprintf("backdrop_url = $%d", argIdx))
		args = append(args, *input.BackdropURL)
		argIdx++
	}
	if input.PosterThumbhash != nil {
		sets = append(sets, fmt.Sprintf("poster_thumbhash = $%d", argIdx))
		args = append(args, *input.PosterThumbhash)
		argIdx++
	}
	if input.BackdropThumbhash != nil {
		sets = append(sets, fmt.Sprintf("backdrop_thumbhash = $%d", argIdx))
		args = append(args, *input.BackdropThumbhash)
		argIdx++
	}
	if input.PosterAutoGenerated != nil {
		sets = append(sets, fmt.Sprintf("poster_auto_generated = $%d", argIdx))
		args = append(args, *input.PosterAutoGenerated)
		argIdx++
	}
	if input.PosterFromTemplate != nil {
		sets = append(sets, fmt.Sprintf("poster_from_template = $%d", argIdx))
		args = append(args, *input.PosterFromTemplate)
		argIdx++
	}
	if input.SourceURL != nil {
		sets = append(sets, fmt.Sprintf("source_url = $%d", argIdx))
		args = append(args, *input.SourceURL)
		argIdx++
	}
	if len(input.QueryDefinition) > 0 {
		sets = append(sets, fmt.Sprintf("query_definition = $%d", argIdx))
		args = append(args, input.QueryDefinition)
		argIdx++
	}
	if len(input.SortConfig) > 0 {
		sets = append(sets, fmt.Sprintf("sort_config = $%d", argIdx))
		args = append(args, input.SortConfig)
		argIdx++
	}
	if len(input.SourceConfig) > 0 {
		sets = append(sets, fmt.Sprintf("source_config = $%d", argIdx))
		args = append(args, input.SourceConfig)
		argIdx++
	}
	if input.ManagementMode != nil {
		sets = append(sets, fmt.Sprintf("management_mode = $%d", argIdx))
		args = append(args, *input.ManagementMode)
		argIdx++
	}
	if input.ManagementSource != nil {
		sets = append(sets, fmt.Sprintf("management_source = $%d", argIdx))
		args = append(args, *input.ManagementSource)
		argIdx++
	}
	if input.ManagementKey != nil {
		sets = append(sets, fmt.Sprintf("management_key = $%d", argIdx))
		args = append(args, *input.ManagementKey)
		argIdx++
	}
	if input.SyncSchedule != nil {
		if *input.SyncSchedule == "" {
			// Clearing schedule: null both columns.
			sets = append(sets, fmt.Sprintf("sync_schedule = $%d", argIdx))
			args = append(args, nil)
			argIdx++
			sets = append(sets, fmt.Sprintf("next_sync_at = $%d", argIdx))
			args = append(args, nil)
			argIdx++
		} else {
			sets = append(sets, fmt.Sprintf("sync_schedule = $%d", argIdx))
			args = append(args, *input.SyncSchedule)
			argIdx++
			sets = append(sets, fmt.Sprintf("next_sync_at = $%d", argIdx))
			args = append(args, computeNextSyncAt(input.SyncSchedule))
			argIdx++
		}
	}
	// Only set NextSyncAt directly if SyncSchedule was not already handled above
	// (which computes next_sync_at automatically).
	if input.NextSyncAt != nil && input.SyncSchedule == nil {
		sets = append(sets, fmt.Sprintf("next_sync_at = $%d", argIdx))
		args = append(args, *input.NextSyncAt)
		argIdx++
	}

	if len(sets) == 0 && input.LibraryIDs == nil && input.SetGroupID == nil && input.ExpectedRevision == nil {
		_, err := r.GetByID(ctx, input.ID)
		return err
	}

	return (libraryCollectionMutation{pool: r.pool, collectionID: input.ID}).run(ctx, input.ExpectedRevision, func(tx pgx.Tx) error {
		if err := lockLibraryCollectionParent(ctx, tx, input.ID); err != nil {
			return err
		}

		if input.LibraryIDs != nil || input.SetGroupID != nil {
			var requested []int
			if input.LibraryIDs != nil {
				requested = normalizeCollectionLibraryIDs(0, *input.LibraryIDs)
			}
			if err := lockLibraryCollectionMembershipOrders(ctx, tx, input.ID, requested); err != nil {
				return err
			}
		}

		if len(sets) > 0 {
			query := fmt.Sprintf("UPDATE library_collections SET %s, updated_at = NOW() WHERE id = $%d", strings.Join(sets, ", "), argIdx)
			queryArgs := append(slices.Clone(args), input.ID)
			tag, err := tx.Exec(ctx, query, queryArgs...)
			if err != nil {
				return fmt.Errorf("updating library collection: %w", err)
			}
			if tag.RowsAffected() == 0 {
				return ErrLibraryCollectionNotFound
			}
		}
		var updatedLibraryIDs []int
		if input.LibraryIDs != nil {
			updatedLibraryIDs = normalizeCollectionLibraryIDs(0, *input.LibraryIDs)
			if _, err := tx.Exec(ctx, `
			DELETE FROM library_collection_libraries
			WHERE collection_id = $1
			  AND NOT (library_id = ANY($2::bigint[]))
		`, input.ID, updatedLibraryIDs); err != nil {
				return fmt.Errorf("deleting removed collection library scopes: %w", err)
			}
			for _, libraryID := range updatedLibraryIDs {
				if _, err := tx.Exec(ctx, `
				INSERT INTO library_collection_libraries (collection_id, library_id, group_id, sort_order)
				SELECT $1, $2, NULL,
				       COALESCE((
				           SELECT MAX(sort_order) + 1
				           FROM library_collection_libraries
				           WHERE library_id = $2 AND group_id IS NULL
				       ), 0)
				ON CONFLICT (collection_id, library_id) DO NOTHING
			`, input.ID, libraryID); err != nil {
					return fmt.Errorf("writing collection library scope: %w", err)
				}
			}
			legacyLibraryID := 0
			if len(updatedLibraryIDs) > 0 {
				legacyLibraryID = updatedLibraryIDs[0]
			}
			if _, err := tx.Exec(ctx, "UPDATE library_collections SET library_id = $2 WHERE id = $1", input.ID, legacyLibraryID); err != nil {
				return fmt.Errorf("updating legacy library_id: %w", err)
			}
		}
		if input.SetGroupID != nil {
			targetGroupID := *input.SetGroupID
			targetLibraryIDs := updatedLibraryIDs
			if targetGroupID != nil {
				var (
					libraryID int
					kind      models.LibraryCollectionGroupKind
				)
				if err := tx.QueryRow(ctx, `
				SELECT library_id, kind
				FROM library_collection_groups
				WHERE id = $1
			`, *targetGroupID).Scan(&libraryID, &kind); err != nil {
					if errors.Is(err, pgx.ErrNoRows) {
						return ErrLibraryCollectionGroupNotFound
					}
					return fmt.Errorf("loading collection group: %w", err)
				}
				if kind == models.GroupKindUserCollections {
					return fmt.Errorf("user-collections group cannot accept admin collections")
				}
				targetLibraryIDs = []int{libraryID}
			} else if input.LibraryIDs == nil {
				rows, err := tx.Query(ctx, `
				SELECT library_id
				FROM library_collection_libraries
				WHERE collection_id = $1
				ORDER BY library_id ASC
			`, input.ID)
				if err != nil {
					return fmt.Errorf("loading collection memberships for group update: %w", err)
				}
				for rows.Next() {
					var libraryID int
					if err := rows.Scan(&libraryID); err != nil {
						rows.Close()
						return fmt.Errorf("scanning collection membership: %w", err)
					}
					targetLibraryIDs = append(targetLibraryIDs, libraryID)
				}
				rows.Close()
				if err := rows.Err(); err != nil {
					return fmt.Errorf("iterating collection memberships: %w", err)
				}
			}

			for _, libraryID := range targetLibraryIDs {
				tag, err := tx.Exec(ctx, `
				UPDATE library_collection_libraries
				SET group_id = $1,
				    sort_order = COALESCE((
				        SELECT MAX(sort_order) + 1
				        FROM library_collection_libraries
				        WHERE library_id = $2
				          AND group_id IS NOT DISTINCT FROM $1
				    ), 0),
				    updated_at = NOW()
				WHERE collection_id = $3 AND library_id = $2
			`, targetGroupID, libraryID, input.ID)
				if err != nil {
					return fmt.Errorf("updating collection group membership: %w", err)
				}
				if tag.RowsAffected() == 0 {
					return ErrLibraryCollectionNotFound
				}
			}
		}
		return nil
	})
}

func (r *LibraryCollectionRepository) Delete(ctx context.Context, id string) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("beginning library collection deletion: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	var lockedID string
	if err := tx.QueryRow(ctx, `SELECT id FROM library_collections WHERE id=$1 FOR UPDATE`, id).Scan(&lockedID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrLibraryCollectionNotFound
		}
		return fmt.Errorf("locking library collection for deletion: %w", err)
	}
	sourceKey := "collection:" + id
	if err := captureCollectionVirtualItems(ctx, tx, sourceKey); err != nil {
		return err
	}
	if _, err := tx.Exec(ctx, `DELETE FROM virtual_media_source_claims WHERE source_key=$1`, sourceKey); err != nil {
		return fmt.Errorf("clearing deleted collection virtual claims: %w", err)
	}
	if err := reconcileAffectedVirtualMetadataOwnership(ctx, tx); err != nil {
		return err
	}
	if _, err := tx.Exec(ctx, `DELETE FROM library_collections WHERE id=$1`, id); err != nil {
		return fmt.Errorf("deleting library collection: %w", err)
	}
	if err := cleanupUnclaimedCollectionVirtualMedia(ctx, tx); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("committing library collection deletion: %w", err)
	}
	return nil
}

var ErrCollectionSyncConfigurationChanged = errors.New("collection configuration changed during sync preparation")

// acceptPreparedItemsPostLockHook, when non-nil, runs after AcceptPreparedItems
// has acquired its advisory locks and before it materializes or mutates
// membership. It is nil in production; tests use it to inspect the
// transaction's advisory-lock footprint while the transaction is paused.
var acceptPreparedItemsPostLockHook func()

func (r *LibraryCollectionRepository) AcceptPreparedItems(ctx context.Context, snapshot *models.LibraryCollection, members []LibraryCollectionItemInput, prepared map[string]preparedCollectionItem, items *ItemRepository) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback(ctx) }()
	var valid bool
	if err := tx.QueryRow(ctx, `
		SELECT source_config = $2::jsonb AND COALESCE(source_url, '') = $3
		       AND library_id = $4 AND collection_type = $5
		FROM library_collections WHERE id = $1 FOR UPDATE`, snapshot.ID, snapshot.SourceConfig, snapshot.SourceURL, snapshot.LibraryID, snapshot.CollectionType).Scan(&valid); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrLibraryCollectionNotFound
		}
		return err
	}
	rows, err := tx.Query(ctx, `SELECT library_id FROM library_collection_libraries WHERE collection_id=$1 ORDER BY library_id`, snapshot.ID)
	if err != nil {
		return err
	}
	libraries, err := pgx.CollectRows(rows, pgx.RowTo[int])
	if err != nil {
		return err
	}
	expected := slices.Clone(snapshot.LibraryIDs)
	if len(expected) == 0 {
		expected = []int{snapshot.LibraryID}
	}
	if len(libraries) == 0 {
		libraries = []int{snapshot.LibraryID}
	}
	slices.Sort(expected)
	if !valid || !slices.Equal(expected, libraries) {
		return ErrCollectionSyncConfigurationChanged
	}
	sourceKey := "collection:" + snapshot.ID
	if err := captureCollectionVirtualItems(ctx, tx, sourceKey); err != nil {
		return err
	}
	desiredIDs := make([]string, 0, len(members))
	for _, member := range members {
		desiredIDs = append(desiredIDs, member.MediaItemID)
	}
	// Scope the advisory-lock set to the items this transaction actually
	// reads or writes: the captured previous virtual items and the prepared
	// members. Membership changes are already serialized by the collection
	// row lock taken above, which ReplaceItems and RemoveItem also take before
	// any item lock, so current and desired non-virtual members need no
	// per-item advisory lock. Locking the whole membership here consumes
	// roughly three transaction-scoped lock-table entries per member and can
	// exhaust max_locks_per_transaction on a large collection re-sync.
	rows, err = tx.Query(ctx, `SELECT content_id FROM affected_collection_virtual_items`)
	if err != nil {
		return err
	}
	lockIDs, err := pgx.CollectRows(rows, pgx.RowTo[string])
	if err != nil {
		return err
	}
	for id := range prepared {
		lockIDs = append(lockIDs, id)
	}
	if len(lockIDs) > 0 {
		slices.Sort(lockIDs)
		lockIDs = slices.Compact(lockIDs)
		// Content locks first (see lockReleaseContentTx): alias writers take
		// these exclusively, so alias sets observed below cannot change under us.
		for _, id := range lockIDs {
			if err := lockReleaseContentTx(ctx, tx, id, false); err != nil {
				return err
			}
		}
		for _, id := range lockIDs {
			if err := requestlock.LockItem(ctx, tx, id); err != nil {
				return err
			}
		}
	}
	if acceptPreparedItemsPostLockHook != nil {
		acceptPreparedItemsPostLockHook()
	}
	// Phase 1: materialize every member with debt writes deferred, so no
	// new release identity is acquired after the first debt write (see
	// lockReleaseContentTx ordering). Phase 2 below emits all debt rows
	// in deterministic order.
	var debtContentIDs []string
	skipped := make(map[string]string, 0)
	for _, id := range slices.Sorted(slices.Values(desiredIDs)) {
		candidate, ok := prepared[id]
		if !ok || !sourceEnablesVirtualPlayback(snapshot.SourceConfig) {
			continue
		}
		if candidate.item == nil || candidate.item.ContentID != id {
			return errors.New("invalid prepared collection item")
		}
		if _, err := items.ensureVirtualCollectionItemMaterializedTx(ctx, tx, snapshot.ID, candidate.item, libraries, candidate.variants, VirtualMaterializeOptions{accepting: true, releaseSnapshot: candidate.releaseSnapshot, preparedExplicitly: true, deferDebtWrite: true}); err != nil {
			if errors.Is(err, ErrIncompatibleLibrary) {
				// A member whose media type has no compatible target library
				// (e.g. a series in a collection bound only to a movies
				// library) is skipped for this run rather than failing the
				// whole accept: every other member still lands, and the
				// warning travels in the sync run record.
				skipped[id] = err.Error()
				continue
			}
			return err
		}
		debtContentIDs = append(debtContentIDs, id)
	}
	if len(skipped) > 0 {
		filtered := desiredIDs[:0]
		for _, id := range desiredIDs {
			if _, ok := skipped[id]; !ok {
				filtered = append(filtered, id)
			}
		}
		desiredIDs = filtered
		filteredMembers := members[:0]
		for _, member := range members {
			if _, ok := skipped[member.MediaItemID]; !ok {
				filteredMembers = append(filteredMembers, member)
			}
		}
		members = filteredMembers
		var skippedIDs []string
		for id := range skipped {
			skippedIDs = append(skippedIDs, id)
		}
		slices.Sort(skippedIDs)
		slog.WarnContext(ctx, "collection sync: skipped members with no compatible target library",
			"component", "catalog", "collection_id", snapshot.ID, "skipped_count", len(skippedIDs), "skipped_ids", skippedIDs)
	}
	for _, id := range debtContentIDs {
		if err := queueVirtualItemRefreshDebtTx(ctx, tx, id); err != nil {
			return fmt.Errorf("queueing accepted item metadata refresh: %w", err)
		}
	}
	if _, err := tx.Exec(ctx, `DELETE FROM library_collection_items WHERE collection_id=$1`, snapshot.ID); err != nil {
		return err
	}
	seen := make(map[string]bool, len(members))
	for _, member := range members {
		if seen[member.MediaItemID] {
			continue
		}
		if _, err := tx.Exec(ctx, `INSERT INTO library_collection_items(collection_id,media_item_id,position,source_rank) VALUES($1,$2,$3,$4)`, snapshot.ID, member.MediaItemID, len(seen), member.SourceRank); err != nil {
			return err
		}
		seen[member.MediaItemID] = true
	}
	if _, err := tx.Exec(ctx, `DELETE FROM virtual_media_source_claims claim WHERE source_key=$1 AND ($3 OR NOT (content_id=ANY($2::text[])) OR EXISTS (SELECT 1 FROM media_files physical WHERE physical.content_id=claim.content_id AND physical.container IS DISTINCT FROM 'virtual' AND physical.file_path NOT LIKE 'virtual://%'))`, sourceKey, desiredIDs, !sourceEnablesVirtualPlayback(snapshot.SourceConfig)); err != nil {
		return err
	}
	if err := reconcileAffectedVirtualMetadataOwnership(ctx, tx); err != nil {
		return err
	}
	if err := cleanupUnclaimedCollectionVirtualMedia(ctx, tx); err != nil {
		return err
	}
	if _, err := tx.Exec(ctx, `UPDATE library_collections SET updated_at=NOW() WHERE id=$1`, snapshot.ID); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

func (r *LibraryCollectionRepository) ReplaceItems(ctx context.Context, collectionID string, items []LibraryCollectionItemInput) error {
	collectionSourceKey := "collection:" + collectionID
	if len([]byte(collectionSourceKey)) > 128 {
		return fmt.Errorf("collection ID is too long for virtual source ownership")
	}
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("beginning collection item replacement: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	// Shared purge barrier: allows concurrent writers but excludes them
	// during the purge sweep. Taken first so both sides order the shared
	// lock before any row lock.
	if err := requestlock.LockPurgeBarrierShared(ctx, tx); err != nil {
		return fmt.Errorf("lock purge barrier: %w", err)
	}

	// Serialize replacements for one collection and retain the previous
	// membership inside this transaction. Cleanup must be based only on rows
	// removed from this collection; a global "not desired" sweep can delete
	// unrelated collection-owned virtual items.
	var lockedCollectionID string
	if err := tx.QueryRow(ctx, `
		SELECT id FROM library_collections WHERE id=$1 FOR UPDATE`,
		collectionID,
	).Scan(&lockedCollectionID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrLibraryCollectionNotFound
		}
		return fmt.Errorf("locking library collection: %w", err)
	}
	if _, err := tx.Exec(ctx, `DELETE FROM library_collection_items WHERE collection_id=$1`, collectionID); err != nil {
		return fmt.Errorf("clearing collection items: %w", err)
	}

	// Dedupe by media_item_id before inserting. Different source entries can
	// resolve to the same library item (e.g. an IMDb and a TMDB entry pointing
	// at the same local content_id, or one item present in several of the
	// collection's bound folders), and library_collection_items has a composite
	// PK (collection_id, media_item_id). Inserting the same media_item_id twice
	// would raise a duplicate-key violation that fails the whole sync. First
	// occurrence wins, preserving rank order. Position is renumbered over the
	// surviving rows so it stays dense.
	seen := make(map[string]struct{}, len(items))
	position := 0
	for _, item := range items {
		if _, dup := seen[item.MediaItemID]; dup {
			continue
		}
		seen[item.MediaItemID] = struct{}{}
		if _, err := tx.Exec(ctx, `
			INSERT INTO library_collection_items (
				collection_id, media_item_id, position, source_rank
			) VALUES ($1, $2, $3, $4)
		`, collectionID, item.MediaItemID, position, item.SourceRank); err != nil {
			return fmt.Errorf("inserting collection item %s: %w", item.MediaItemID, err)
		}
		position++
	}

	// A collection is an independent owner of the virtual files that it
	// materialized. Rebuild its exact claims transactionally with membership so
	// request cancellation and other provider reconciliation cannot remove a
	// file that the collection still needs.
	if err := captureCollectionVirtualItems(ctx, tx, collectionSourceKey); err != nil {
		return err
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO affected_collection_virtual_items(content_id)
		SELECT media_item_id FROM library_collection_items WHERE collection_id=$1
		ON CONFLICT DO NOTHING`, collectionID); err != nil {
		return fmt.Errorf("capturing current collection virtual items: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		DELETE FROM virtual_media_source_claims
		WHERE source_key=$1`, collectionSourceKey); err != nil {
		return fmt.Errorf("clearing previous collection virtual claims: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO virtual_media_source_claims(
			plugin_installation_id,source_key,content_id,media_folder_id,
			owns_item_metadata,last_seen_at,updated_at
		)
		SELECT DISTINCT
			file_claim.plugin_installation_id,$1,file_claim.content_id,file_claim.media_folder_id,
			false,
			NOW(),NOW()
		FROM (
			SELECT plugin_installation_id, content_id, media_folder_id, file_path
			FROM previous_collection_virtual_files
			UNION
			-- Legacy adoption: files carrying an unscoped legacy claim are
			-- adopted explicitly by identity.
			SELECT legacy_claim.plugin_installation_id, legacy_claim.content_id,
			       legacy_claim.media_folder_id, legacy_claim.file_path
			FROM virtual_media_file_source_claims legacy_claim
			WHERE legacy_claim.source_key = 'collection'
			UNION
			-- Claimless adoption: virtual_collection files with no ownership
			-- claims at all (legacy materialization output) are adopted for
			-- accepted members in target folders. Files claimed by any other
			-- owner are never adopted here. Core-owned files (owner 0) adopt
			-- like plugin-owned ones; local files (NULL owner) never do.
			SELECT mf.virtual_owner_installation_id, mf.content_id,
			       mf.media_folder_id, mf.file_path
			FROM media_files mf
			WHERE mf.probe_source = 'virtual_collection'
			  AND mf.virtual_owner_installation_id >= 0
			  AND NOT EXISTS (
			      SELECT 1 FROM virtual_media_file_source_claims existing_claim
			      WHERE existing_claim.plugin_installation_id = mf.virtual_owner_installation_id
			        AND existing_claim.content_id = mf.content_id
			        AND existing_claim.media_folder_id = mf.media_folder_id
			        AND existing_claim.file_path = mf.file_path
			  )
		) file_claim
		JOIN library_collection_items lci
		  ON lci.collection_id=$2 AND lci.media_item_id=file_claim.content_id
		JOIN library_collection_libraries lcl
		  ON lcl.collection_id=$2 AND lcl.library_id=file_claim.media_folder_id
		WHERE file_claim.plugin_installation_id>=0
		ON CONFLICT(plugin_installation_id,source_key,content_id,media_folder_id)
		DO UPDATE SET
			owns_item_metadata=EXCLUDED.owns_item_metadata,
			last_seen_at=EXCLUDED.last_seen_at,
			staged_until=NULL,
			updated_at=NOW()`, collectionSourceKey, collectionID); err != nil {
		return fmt.Errorf("claiming collection virtual sources: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO virtual_media_file_source_claims(
			plugin_installation_id,source_key,content_id,media_folder_id,
			file_path,last_seen_at,updated_at
		)
		SELECT
			file_claim.plugin_installation_id,$1,file_claim.content_id,file_claim.media_folder_id,
			file_claim.file_path,NOW(),NOW()
		FROM (
			SELECT plugin_installation_id, content_id, media_folder_id, file_path
			FROM previous_collection_virtual_files
			UNION
			-- Legacy adoption: see the source-claim rebuild above.
			SELECT legacy_claim.plugin_installation_id, legacy_claim.content_id,
			       legacy_claim.media_folder_id, legacy_claim.file_path
			FROM virtual_media_file_source_claims legacy_claim
			WHERE legacy_claim.source_key = 'collection'
			UNION
			-- Claimless adoption: see the source-claim rebuild above.
			SELECT mf.virtual_owner_installation_id, mf.content_id,
			       mf.media_folder_id, mf.file_path
			FROM media_files mf
			WHERE mf.probe_source = 'virtual_collection'
			  AND mf.virtual_owner_installation_id >= 0
			  AND NOT EXISTS (
			      SELECT 1 FROM virtual_media_file_source_claims existing_claim
			      WHERE existing_claim.plugin_installation_id = mf.virtual_owner_installation_id
			        AND existing_claim.content_id = mf.content_id
			        AND existing_claim.media_folder_id = mf.media_folder_id
			        AND existing_claim.file_path = mf.file_path
			  )
		) file_claim
		JOIN library_collection_items lci
		  ON lci.collection_id=$2 AND lci.media_item_id=file_claim.content_id
		JOIN library_collection_libraries lcl
		  ON lcl.collection_id=$2 AND lcl.library_id=file_claim.media_folder_id
		WHERE file_claim.plugin_installation_id>=0
		ON CONFLICT(plugin_installation_id,source_key,content_id,media_folder_id,file_path)
		DO UPDATE SET last_seen_at=EXCLUDED.last_seen_at,staged_until=NULL,updated_at=NOW()`,
		collectionSourceKey, collectionID); err != nil {
		return fmt.Errorf("claiming collection virtual files: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		UPDATE media_files mf
		SET missing_since = NULL
		FROM virtual_media_file_source_claims file_claim
		JOIN library_collection_items lci ON lci.collection_id = $1 AND lci.media_item_id = file_claim.content_id
		JOIN library_collection_libraries lcl ON lcl.collection_id = $1 AND lcl.library_id = file_claim.media_folder_id
		WHERE file_claim.source_key = $2
		  AND file_claim.plugin_installation_id = mf.virtual_owner_installation_id
		  AND file_claim.content_id = mf.content_id
		  AND file_claim.media_folder_id = mf.media_folder_id
		  AND file_claim.file_path = mf.file_path
		  AND mf.probe_source = 'virtual_collection'`, collectionID, collectionSourceKey); err != nil {
		return fmt.Errorf("activating collection virtual files: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO media_item_libraries(content_id, media_folder_id, first_seen_at)
		SELECT DISTINCT file_claim.content_id, file_claim.media_folder_id, NOW()
		FROM virtual_media_file_source_claims file_claim
		JOIN library_collection_items lci ON lci.collection_id = $1 AND lci.media_item_id = file_claim.content_id
		JOIN library_collection_libraries lcl ON lcl.collection_id = $1 AND lcl.library_id = file_claim.media_folder_id
		WHERE file_claim.source_key = $2
		ON CONFLICT DO NOTHING`, collectionID, collectionSourceKey); err != nil {
		return fmt.Errorf("linking collection virtual items to libraries: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO episode_libraries(episode_id, media_folder_id)
		SELECT DISTINCT mf.episode_id, file_claim.media_folder_id
		FROM virtual_media_file_source_claims file_claim
		JOIN media_files mf ON mf.content_id = file_claim.content_id
		                   AND mf.media_folder_id = file_claim.media_folder_id
		                   AND mf.file_path = file_claim.file_path
		JOIN library_collection_items lci ON lci.collection_id = $1 AND lci.media_item_id = file_claim.content_id
		JOIN library_collection_libraries lcl ON lcl.collection_id = $1 AND lcl.library_id = file_claim.media_folder_id
		WHERE file_claim.source_key = $2
		  AND mf.episode_id IS NOT NULL
		ON CONFLICT DO NOTHING`, collectionID, collectionSourceKey); err != nil {
		return fmt.Errorf("linking collection virtual episodes to libraries: %w", err)
	}
	if err := reconcileAffectedVirtualMetadataOwnership(ctx, tx); err != nil {
		return err
	}
	if err := cleanupUnclaimedCollectionVirtualMedia(ctx, tx); err != nil {
		return err
	}

	if _, err := tx.Exec(ctx, "UPDATE library_collections SET updated_at = NOW() WHERE id = $1", collectionID); err != nil {
		return fmt.Errorf("touching library collection: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("committing collection item replacement: %w", err)
	}
	return nil
}

// ListItemIDsPage answers one window of a collection's stored item order:
// the media item IDs at positions [offset, offset+limit) in the same order
// ListItems uses, and whether stored positions follow the window. It probes
// one row past the window so a caller never has to count the collection to
// learn that. A limit of zero or less answers an empty window.
func (r *LibraryCollectionRepository) ListItemIDsPage(ctx context.Context, collectionID string, limit, offset int) ([]string, bool, error) {
	if limit <= 0 {
		return []string{}, false, nil
	}
	offset = max(offset, 0)

	rows, err := r.pool.Query(ctx, `
		SELECT media_item_id
		FROM library_collection_items
		WHERE collection_id = $1
		ORDER BY position ASC, source_rank ASC, media_item_id ASC
		LIMIT $2 OFFSET $3
	`, collectionID, limit+1, offset)
	if err != nil {
		return nil, false, fmt.Errorf("listing collection item page: %w", err)
	}
	defer rows.Close()

	ids := make([]string, 0, limit+1)
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, false, fmt.Errorf("scanning collection item page: %w", err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		return nil, false, fmt.Errorf("iterating collection item page: %w", err)
	}

	hasMore := len(ids) > limit
	if hasMore {
		ids = ids[:limit]
	}
	return ids, hasMore, nil
}

func captureCollectionVirtualItems(ctx context.Context, tx pgx.Tx, sourceKey string) error {
	if _, err := tx.Exec(ctx, `
		CREATE TEMP TABLE affected_collection_virtual_items(
			content_id text PRIMARY KEY
		) ON COMMIT DROP`); err != nil {
		return fmt.Errorf("create affected collection virtual items: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO affected_collection_virtual_items(content_id)
		SELECT DISTINCT content_id
		FROM virtual_media_source_claims
		WHERE source_key=$1`, sourceKey); err != nil {
		return fmt.Errorf("capturing previous collection virtual items: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		CREATE TEMP TABLE previous_collection_virtual_files ON COMMIT DROP AS
		SELECT plugin_installation_id,content_id,media_folder_id,file_path
		FROM virtual_media_file_source_claims
		WHERE source_key=$1`, sourceKey); err != nil {
		return fmt.Errorf("capturing previous collection virtual files: %w", err)
	}
	return nil
}

// reconcileAffectedVirtualMetadataOwnership guarantees one compatibility
// owner for each affected virtual-only item. Collection claims describe file
// lifecycle, not competing metadata authorities, so an existing owner wins;
// otherwise the newest remaining claim is promoted deterministically. Local
// files always remain authoritative and clear the compatibility owner fields.
func reconcileAffectedVirtualMetadataOwnership(ctx context.Context, tx pgx.Tx) error {
	if _, err := tx.Exec(ctx, `
		WITH chosen AS (
			SELECT DISTINCT ON (claim.content_id)
				claim.content_id,claim.plugin_installation_id,claim.source_key,
				claim.media_folder_id,claim.last_seen_at
			FROM virtual_media_source_claims claim
			JOIN affected_collection_virtual_items affected
			  ON affected.content_id=claim.content_id
			WHERE NOT EXISTS (
				SELECT 1 FROM media_files physical
				WHERE physical.content_id=claim.content_id
				  AND physical.container IS DISTINCT FROM 'virtual'
				  AND physical.file_path NOT LIKE 'virtual://%'
			)
			ORDER BY claim.content_id,claim.owns_item_metadata DESC,
			         claim.last_seen_at DESC,claim.plugin_installation_id,
			         claim.source_key,claim.media_folder_id
		)
		UPDATE virtual_media_source_claims claim
		SET owns_item_metadata=(
			chosen.plugin_installation_id IS NOT NULL
			AND claim.plugin_installation_id=chosen.plugin_installation_id
			AND claim.source_key=chosen.source_key
			AND claim.media_folder_id=chosen.media_folder_id
		),updated_at=CASE
			WHEN claim.owns_item_metadata IS DISTINCT FROM (
				chosen.plugin_installation_id IS NOT NULL
				AND claim.plugin_installation_id=chosen.plugin_installation_id
				AND claim.source_key=chosen.source_key
				AND claim.media_folder_id=chosen.media_folder_id
			) THEN NOW() ELSE claim.updated_at END
		FROM affected_collection_virtual_items affected
		LEFT JOIN chosen ON chosen.content_id=affected.content_id
		WHERE claim.content_id=affected.content_id`); err != nil {
		return fmt.Errorf("reconciling collection virtual metadata claims: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		WITH chosen AS (
			SELECT DISTINCT ON (claim.content_id)
				claim.content_id,claim.plugin_installation_id,claim.source_key,
				claim.last_seen_at
			FROM virtual_media_source_claims claim
			JOIN affected_collection_virtual_items affected
			  ON affected.content_id=claim.content_id
			WHERE claim.owns_item_metadata
			ORDER BY claim.content_id,claim.last_seen_at DESC,
			         claim.plugin_installation_id,claim.source_key
		)
		UPDATE media_items item
		SET virtual_owner_installation_id=chosen.plugin_installation_id,
			virtual_source=COALESCE(chosen.source_key,''),
			virtual_last_seen_at=COALESCE(chosen.last_seen_at, item.virtual_last_seen_at),
			updated_at=NOW()
		FROM affected_collection_virtual_items affected
		LEFT JOIN chosen ON chosen.content_id=affected.content_id
		WHERE item.content_id=affected.content_id`); err != nil {
		return fmt.Errorf("reconciling collection virtual metadata owner: %w", err)
	}
	return nil
}

func cleanupUnclaimedCollectionVirtualMedia(ctx context.Context, tx pgx.Tx) error {
	if _, err := tx.Exec(ctx, `
		DELETE FROM media_files mf
		USING previous_collection_virtual_files previous
		WHERE mf.virtual_owner_installation_id=previous.plugin_installation_id
		  AND mf.content_id=previous.content_id
		  AND mf.media_folder_id=previous.media_folder_id
		  AND mf.file_path=previous.file_path
		  AND (mf.container='virtual' OR mf.file_path LIKE 'virtual://%')
		  AND NOT EXISTS (
		      SELECT 1 FROM virtual_media_file_source_claims claim
		      WHERE claim.plugin_installation_id=mf.virtual_owner_installation_id
		        AND claim.content_id=mf.content_id
		        AND claim.media_folder_id=mf.media_folder_id
		        AND claim.file_path=mf.file_path
		  )`); err != nil {
		return fmt.Errorf("deleting unclaimed collection virtual files: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		DELETE FROM media_item_libraries mil
		WHERE mil.content_id IN (SELECT content_id FROM affected_collection_virtual_items)
		  AND NOT EXISTS (
		      SELECT 1 FROM media_files mf
		      WHERE mf.content_id = mil.content_id
		        AND mf.media_folder_id = mil.media_folder_id
		  )
		  AND NOT EXISTS (
		      SELECT 1 FROM virtual_media_source_claims claim
		      WHERE claim.content_id = mil.content_id AND claim.media_folder_id = mil.media_folder_id
		  )
		  AND EXISTS (
		      SELECT 1 FROM previous_collection_virtual_files previous
		      WHERE previous.content_id = mil.content_id AND previous.media_folder_id = mil.media_folder_id
		  )
		  AND NOT EXISTS (
		      SELECT 1
		      FROM library_collection_items lci
		      JOIN library_collection_libraries lcl ON lcl.collection_id = lci.collection_id
		      WHERE lci.media_item_id = mil.content_id
		        AND lcl.library_id = mil.media_folder_id
		  )`); err != nil {
		return fmt.Errorf("deleting unreferenced collection library links: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		DELETE FROM episode_libraries el
		WHERE el.episode_id IN (
		    SELECT ep.content_id FROM episodes ep
		    WHERE ep.series_id IN (SELECT content_id FROM affected_collection_virtual_items)
		)
		  AND NOT EXISTS (
		      SELECT 1 FROM media_files mf
		      WHERE mf.episode_id = el.episode_id
		        AND mf.media_folder_id = el.media_folder_id
		  )`); err != nil {
		return fmt.Errorf("deleting unreferenced collection episode library links: %w", err)
	}
	rows, err := tx.Query(ctx, `
		DELETE FROM media_items mi
		WHERE mi.content_id IN (SELECT content_id FROM affected_collection_virtual_items)
		  AND NOT EXISTS (SELECT 1 FROM library_collection_items membership WHERE membership.media_item_id=mi.content_id)
		  AND NOT EXISTS (SELECT 1 FROM media_files mf WHERE mf.content_id=mi.content_id)
		  AND NOT EXISTS (SELECT 1 FROM virtual_media_source_claims claim WHERE claim.content_id=mi.content_id)
		RETURNING mi.content_id`)
	if err != nil {
		return fmt.Errorf("cleaning removed collection virtual items: %w", err)
	}
	deletedIDs, err := pgx.CollectRows(rows, pgx.RowTo[string])
	if err != nil {
		return fmt.Errorf("collecting removed collection virtual items: %w", err)
	}
	if err := EnqueueSearchIndexDeletes(ctx, tx, deletedIDs); err != nil {
		return fmt.Errorf("enqueueing removed collection search deletes: %w", err)
	}
	return nil
}

func (r *LibraryCollectionRepository) ListItems(ctx context.Context, collectionID string) ([]*models.LibraryCollectionItem, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT collection_id, media_item_id, position, source_rank, created_at, updated_at
		FROM library_collection_items
		WHERE collection_id = $1
		ORDER BY position ASC, source_rank ASC, media_item_id ASC
	`, collectionID)
	if err != nil {
		return nil, fmt.Errorf("listing collection items: %w", err)
	}
	defer rows.Close()

	var items []*models.LibraryCollectionItem
	for rows.Next() {
		var item models.LibraryCollectionItem
		if err := rows.Scan(
			&item.CollectionID,
			&item.MediaItemID,
			&item.Position,
			&item.SourceRank,
			&item.CreatedAt,
			&item.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("scanning collection item: %w", err)
		}
		items = append(items, &item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating collection items: %w", err)
	}

	return items, nil
}

// AddItem inserts or upserts a single item in a manual collection. The
// caller is responsible for verifying the collection's type before invoking
// this — synced collections (mdblist/tmdb/trakt) overwrite manual edits on
// their next sync.
func (r *LibraryCollectionRepository) AddItem(ctx context.Context, collectionID, mediaItemID string, position int) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("beginning add collection item: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if err := lockLibraryCollectionParent(ctx, tx, collectionID); err != nil {
		return err
	}

	if _, err := tx.Exec(ctx, `
		INSERT INTO library_collection_items (collection_id, media_item_id, position, source_rank)
		VALUES ($1, $2, $3, 0)
		ON CONFLICT (collection_id, media_item_id)
		  DO UPDATE SET position = EXCLUDED.position
	`, collectionID, mediaItemID, position); err != nil {
		return fmt.Errorf("upserting collection item: %w", err)
	}
	if _, err := tx.Exec(ctx, "UPDATE library_collections SET updated_at = NOW() WHERE id = $1", collectionID); err != nil {
		return fmt.Errorf("touching library collection: %w", err)
	}
	return tx.Commit(ctx)
}

// RemoveItem deletes a single item from a collection. It locks the collection first,
// removes membership, releases this collection's source and file claims for the item,
// reconciles metadata ownership, and cleans up any virtual files and catalog items
// orphaned by the removal.
func (r *LibraryCollectionRepository) RemoveItem(ctx context.Context, collectionID, mediaItemID string) error {
	collectionSourceKey := "collection:" + collectionID
	if len([]byte(collectionSourceKey)) > 128 {
		return fmt.Errorf("collection ID is too long for virtual source ownership")
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("beginning remove collection item: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// Lock 1: Lock collection first to coordinate with concurrent sync/repair/delete.
	var lockedCollectionID string
	if err := tx.QueryRow(ctx, `
		SELECT id FROM library_collections WHERE id=$1 FOR UPDATE`,
		collectionID,
	).Scan(&lockedCollectionID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrLibraryCollectionNotFound
		}
		return fmt.Errorf("locking library collection: %w", err)
	}

	if err := requestlock.LockItem(ctx, tx, mediaItemID); err != nil {
		return fmt.Errorf("locking removed collection item: %w", err)
	}

	// Capture previous collection virtual files for this item before claims are removed.
	if _, err := tx.Exec(ctx, `
		CREATE TEMP TABLE previous_collection_virtual_files(
			plugin_installation_id bigint,
			content_id text,
			media_folder_id int,
			file_path text
		) ON COMMIT DROP`); err != nil {
		return fmt.Errorf("create previous collection virtual files: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO previous_collection_virtual_files(
			plugin_installation_id, content_id, media_folder_id, file_path
		)
		SELECT plugin_installation_id, content_id, media_folder_id, file_path
		FROM virtual_media_file_source_claims
		WHERE source_key = $1 AND content_id = $2`, collectionSourceKey, mediaItemID); err != nil {
		return fmt.Errorf("capturing previous collection virtual files: %w", err)
	}

	// Capture affected item for metadata ownership reconciliation, but only
	// when this collection provably owned virtual state. Ordinary
	// metadata-only members must survive removal as catalog rows.
	if _, err := tx.Exec(ctx, `
		CREATE TEMP TABLE affected_collection_virtual_items(
			content_id text PRIMARY KEY
		) ON COMMIT DROP`); err != nil {
		return fmt.Errorf("create affected collection virtual items: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO affected_collection_virtual_items(content_id)
		SELECT $1
		WHERE EXISTS (
			SELECT 1 FROM virtual_media_source_claims
			WHERE source_key = $2 AND content_id = $1
		) OR EXISTS (
			SELECT 1 FROM virtual_media_file_source_claims
			WHERE source_key = $2 AND content_id = $1
		) ON CONFLICT DO NOTHING`, mediaItemID, collectionSourceKey); err != nil {
		return fmt.Errorf("capturing affected collection virtual item: %w", err)
	}

	// Delete collection membership. A non-member removal is a no-op and must
	// never trigger cleanup of an unrelated catalog item.
	tag, err := tx.Exec(ctx, `
		DELETE FROM library_collection_items
		WHERE collection_id = $1 AND media_item_id = $2
	`, collectionID, mediaItemID)
	if err != nil {
		return fmt.Errorf("deleting collection item: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrCollectionItemNotMember
	}

	// Delete this collection's file claims and source claims for this item.
	if _, err := tx.Exec(ctx, `
		DELETE FROM virtual_media_file_source_claims
		WHERE source_key = $1 AND content_id = $2`, collectionSourceKey, mediaItemID); err != nil {
		return fmt.Errorf("deleting collection virtual file claims: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		DELETE FROM virtual_media_source_claims
		WHERE source_key = $1 AND content_id = $2`, collectionSourceKey, mediaItemID); err != nil {
		return fmt.Errorf("deleting collection virtual source claims: %w", err)
	}

	// Reconcile metadata ownership and clean unclaimed virtual media.
	if err := reconcileAffectedVirtualMetadataOwnership(ctx, tx); err != nil {
		return err
	}
	if err := cleanupUnclaimedCollectionVirtualMedia(ctx, tx); err != nil {
		return err
	}

	if _, err := tx.Exec(ctx, "UPDATE library_collections SET updated_at = NOW() WHERE id = $1", collectionID); err != nil {
		return fmt.Errorf("touching library collection: %w", err)
	}
	return tx.Commit(ctx)
}

// ReorderItems sets each item's position to its index in the supplied list.
// The list must be a permutation of the existing membership.
func (r *LibraryCollectionRepository) ReorderItems(ctx context.Context, collectionID string, orderedMediaItemIDs []string) error {
	return r.reorderItems(ctx, collectionID, orderedMediaItemIDs, nil)
}
func (r *LibraryCollectionRepository) ReorderItemsIfRevision(ctx context.Context, collectionID string, orderedMediaItemIDs []string, expected int64) error {
	return r.reorderItems(ctx, collectionID, orderedMediaItemIDs, &expected)
}
func (r *LibraryCollectionRepository) reorderItems(ctx context.Context, collectionID string, orderedMediaItemIDs []string, expected *int64) error {
	if collectionutil.HasDuplicateOrderedIDs(orderedMediaItemIDs) {
		return fmt.Errorf("ordered_ids contains duplicates")
	}

	return (libraryCollectionMutation{pool: r.pool, collectionID: collectionID}).run(ctx, expected, func(tx pgx.Tx) error {
		if expected != nil {
			if _, err := lockManualLibraryCollection(ctx, tx, collectionID); err != nil {
				return err
			}
		} else if err := lockLibraryCollectionParent(ctx, tx, collectionID); err != nil {
			return err
		}

		var updated, total int
		if err := tx.QueryRow(ctx, `
		WITH supplied AS (
		  SELECT id, pos FROM unnest($1::text[]) WITH ORDINALITY AS u(id, pos)
		),
		upd AS (
		  UPDATE library_collection_items t
		  SET position = supplied.pos - 1
		  FROM supplied
		  WHERE t.collection_id = $2 AND t.media_item_id = supplied.id
		  RETURNING 1
		)
		SELECT (SELECT count(*) FROM upd),
		       (SELECT count(*) FROM library_collection_items WHERE collection_id = $2)
	`, orderedMediaItemIDs, collectionID).Scan(&updated, &total); err != nil {
			return fmt.Errorf("reordering collection items: %w", err)
		}
		if updated != len(orderedMediaItemIDs) || updated != total {
			return collectionutil.ErrOrderedIDsMismatch
		}

		if _, err := tx.Exec(ctx, "UPDATE library_collections SET updated_at = NOW() WHERE id = $1", collectionID); err != nil {
			return fmt.Errorf("touching library collection: %w", err)
		}
		return nil
	})
}

// ReorderCollections sets each membership row's sort_order to its index in the
// supplied list, scoped to the given library. The list must be a permutation of
// the collections currently exposed in that library, or when groupID is non-nil
// just the memberships in that group.
func (r *LibraryCollectionRepository) ReorderCollections(ctx context.Context, libraryID int, groupID *string, orderedIDs []string) error {
	return r.reorderCollections(ctx, libraryID, groupID, orderedIDs, nil)
}
func (r *LibraryCollectionRepository) ReorderCollectionsIfRevision(ctx context.Context, libraryID int, groupID *string, orderedIDs []string, expected int64) error {
	return r.reorderCollections(ctx, libraryID, groupID, orderedIDs, &expected)
}
func (r *LibraryCollectionRepository) reorderCollections(ctx context.Context, libraryID int, groupID *string, orderedIDs []string, expected *int64) error {
	if collectionutil.HasDuplicateOrderedIDs(orderedIDs) {
		return fmt.Errorf("ordered_ids contains duplicates")
	}

	return (libraryCollectionMutation{pool: r.pool, libraryID: libraryID}).run(ctx, expected, func(tx pgx.Tx) error {
		if err := lockLibraryCollectionParents(ctx, tx, libraryID); err != nil {
			return err
		}

		var updated, total int
		if err := tx.QueryRow(ctx, `
		WITH supplied AS (
		  SELECT id, pos FROM unnest($1::text[]) WITH ORDINALITY AS u(id, pos)
		),
		upd AS (
		  UPDATE library_collection_libraries t
		  SET sort_order = supplied.pos - 1, updated_at = NOW()
		  FROM supplied
		  WHERE t.collection_id = supplied.id
		    AND t.library_id = $2
		    AND t.group_id IS NOT DISTINCT FROM $3
		  RETURNING 1
		)
		SELECT (SELECT count(*) FROM upd),
		       (SELECT count(*) FROM library_collection_libraries
		         WHERE library_id = $2
		           AND group_id IS NOT DISTINCT FROM $3)
	`, orderedIDs, libraryID, groupID).Scan(&updated, &total); err != nil {
			return fmt.Errorf("reordering collections: %w", err)
		}
		if updated != len(orderedIDs) || updated != total {
			return collectionutil.ErrOrderedIDsMismatch
		}

		return nil
	})
}

// ListByGroup returns all visible collections in a library that belong to the
// given group. Pass nil for groupID to list the implicit Ungrouped bucket.
func (r *LibraryCollectionRepository) ListByGroup(ctx context.Context, libraryID int, groupID *string) ([]*models.LibraryCollection, error) {
	rows, err := r.pool.Query(ctx, fmt.Sprintf(`
		SELECT %s
		FROM library_collections lc
		JOIN library_collection_libraries scope_lcl
		  ON scope_lcl.collection_id = lc.id AND scope_lcl.library_id = $1
		LEFT JOIN library_collection_items lci ON lci.collection_id = lc.id
		LEFT JOIN library_collection_libraries lcl ON lcl.collection_id = lc.id
		WHERE lc.visibility = 'visible'
		  AND scope_lcl.group_id IS NOT DISTINCT FROM $2
		GROUP BY lc.id, scope_lcl.group_id, scope_lcl.sort_order
		ORDER BY scope_lcl.sort_order ASC, lc.title ASC
	`, libraryCollectionColumns), libraryID, groupID)
	if err != nil {
		return nil, fmt.Errorf("listing collections by group: %w", err)
	}
	defer rows.Close()
	return scanLibraryCollections(rows)
}

type MoveAndReorderInput struct {
	ExpectedRevision *int64
	LibraryID        int
	TargetGroupID    *string
	OrderedIDs       []string
	Strict           bool
}

type StrictReorderError struct {
	MissingIDs []string
}

func (e *StrictReorderError) Error() string {
	return fmt.Sprintf("strict reorder: %d collection(s) currently in this group are missing from the request", len(e.MissingIDs))
}

// MoveAndReorder atomically assigns every collection in OrderedIDs to
// TargetGroupID within one library and rewrites the target group's sort_order.
func (r *LibraryCollectionRepository) MoveAndReorder(ctx context.Context, in MoveAndReorderInput) error {
	if collectionutil.HasDuplicateOrderedIDs(in.OrderedIDs) {
		return fmt.Errorf("ordered_ids contains duplicates")
	}

	return (libraryCollectionMutation{pool: r.pool, libraryID: in.LibraryID}).run(ctx, in.ExpectedRevision, func(tx pgx.Tx) error {
		if err := lockLibraryCollectionParents(ctx, tx, in.LibraryID); err != nil {
			return err
		}

		if in.TargetGroupID != nil {
			var kind models.LibraryCollectionGroupKind
			if err := tx.QueryRow(ctx, `
			SELECT kind
			FROM library_collection_groups
			WHERE id = $1 AND library_id = $2
		`, *in.TargetGroupID, in.LibraryID).Scan(&kind); err != nil {
				if errors.Is(err, pgx.ErrNoRows) {
					return ErrLibraryCollectionGroupNotFound
				}
				return fmt.Errorf("loading target group: %w", err)
			}
			if kind == models.GroupKindUserCollections {
				return fmt.Errorf("user-collections group cannot accept admin collections")
			}
		}

		rows, err := tx.Query(ctx, `
		SELECT collection_id, group_id
		FROM library_collection_libraries
		WHERE library_id = $1
		  AND collection_id = ANY($2::text[])
		FOR UPDATE
	`, in.LibraryID, in.OrderedIDs)
		if err != nil {
			return fmt.Errorf("locking collection memberships: %w", err)
		}
		seen := map[string]*string{}
		sourceGroups := map[string]*string{}
		for rows.Next() {
			var id string
			var groupID *string
			if err := rows.Scan(&id, &groupID); err != nil {
				rows.Close()
				return fmt.Errorf("scanning collection membership: %w", err)
			}
			seen[id] = groupID
			sourceGroups[groupKey(groupID)] = groupID
		}
		rows.Close()
		if err := rows.Err(); err != nil {
			return fmt.Errorf("iterating collection memberships: %w", err)
		}
		for _, id := range in.OrderedIDs {
			if _, ok := seen[id]; !ok {
				return fmt.Errorf("collection %q not found in library %d", id, in.LibraryID)
			}
		}

		if in.Strict {
			rows, err := tx.Query(ctx, `
			SELECT collection_id
			FROM library_collection_libraries
			WHERE library_id = $1
			  AND group_id IS NOT DISTINCT FROM $2
		`, in.LibraryID, in.TargetGroupID)
			if err != nil {
				return fmt.Errorf("listing target group membership: %w", err)
			}
			want := map[string]bool{}
			for _, id := range in.OrderedIDs {
				want[id] = true
			}
			var missing []string
			for rows.Next() {
				var id string
				if err := rows.Scan(&id); err != nil {
					rows.Close()
					return fmt.Errorf("scanning target group membership: %w", err)
				}
				if !want[id] {
					missing = append(missing, id)
				}
			}
			rows.Close()
			if err := rows.Err(); err != nil {
				return fmt.Errorf("iterating target group membership: %w", err)
			}
			if len(missing) > 0 {
				return &StrictReorderError{MissingIDs: missing}
			}
		}

		for idx, id := range in.OrderedIDs {
			if _, err := tx.Exec(ctx, `
			UPDATE library_collection_libraries
			SET group_id = $1, sort_order = $2, updated_at = NOW()
			WHERE library_id = $3 AND collection_id = $4
		`, in.TargetGroupID, idx, in.LibraryID, id); err != nil {
				return fmt.Errorf("updating collection membership: %w", err)
			}
		}

		sourceGroups[groupKey(in.TargetGroupID)] = in.TargetGroupID
		for _, groupID := range sourceGroups {
			if err := compactCollectionMembershipOrder(ctx, tx, in.LibraryID, groupID); err != nil {
				return err
			}
		}

		return nil
	})
}

func (r *LibraryCollectionRepository) RecordSyncRun(ctx context.Context, input RecordLibraryCollectionSyncRunInput) (*models.LibraryCollectionSyncRun, error) {
	if len(input.Warnings) == 0 {
		input.Warnings = json.RawMessage(`[]`)
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("beginning sync run insert: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	id, err := idgen.NextID()
	if err != nil {
		return nil, fmt.Errorf("generate id: %w", err)
	}
	var run models.LibraryCollectionSyncRun
	err = tx.QueryRow(ctx, `
		INSERT INTO library_collection_sync_runs (
			id, collection_id, status, message, items_added, items_removed,
			items_matched, items_unmatched, warnings, started_at, completed_at
		) VALUES (
			$1, $2, $3, $4, $5, $6,
			$7, $8, $9, $10, $11
		)
		RETURNING id, collection_id, status, message, items_added, items_removed,
			items_matched, items_unmatched, warnings, started_at, completed_at, created_at
	`,
		id,
		input.CollectionID,
		input.Status,
		input.Message,
		input.ItemsAdded,
		input.ItemsRemoved,
		input.ItemsMatched,
		input.ItemsUnmatched,
		input.Warnings,
		input.StartedAt,
		input.CompletedAt,
	).Scan(
		&run.ID,
		&run.CollectionID,
		&run.Status,
		&run.Message,
		&run.ItemsAdded,
		&run.ItemsRemoved,
		&run.ItemsMatched,
		&run.ItemsUnmatched,
		&run.Warnings,
		&run.StartedAt,
		&run.CompletedAt,
		&run.CreatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("inserting sync run: %w", err)
	}

	lastSyncAt := input.CompletedAt
	if _, err := tx.Exec(ctx, `
		UPDATE library_collections
		SET last_sync_status = $2,
		    last_sync_message = $3,
		    last_sync_at = $4,
		    updated_at = NOW()
		WHERE id = $1
	`, input.CollectionID, input.Status, input.Message, lastSyncAt); err != nil {
		return nil, fmt.Errorf("updating collection sync state: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("committing sync run: %w", err)
	}

	return &run, nil
}

func (r *LibraryCollectionRepository) ListSyncRuns(ctx context.Context, collectionID string, limit int) ([]*models.LibraryCollectionSyncRun, error) {
	if limit <= 0 {
		limit = 20
	}

	rows, err := r.pool.Query(ctx, `
		SELECT id, collection_id, status, message, items_added, items_removed,
		       items_matched, items_unmatched, warnings, started_at, completed_at, created_at
		FROM library_collection_sync_runs
		WHERE collection_id = $1
		ORDER BY created_at DESC
		LIMIT $2
	`, collectionID, limit)
	if err != nil {
		return nil, fmt.Errorf("listing sync runs: %w", err)
	}
	defer rows.Close()

	var runs []*models.LibraryCollectionSyncRun
	for rows.Next() {
		var run models.LibraryCollectionSyncRun
		if err := rows.Scan(
			&run.ID,
			&run.CollectionID,
			&run.Status,
			&run.Message,
			&run.ItemsAdded,
			&run.ItemsRemoved,
			&run.ItemsMatched,
			&run.ItemsUnmatched,
			&run.Warnings,
			&run.StartedAt,
			&run.CompletedAt,
			&run.CreatedAt,
		); err != nil {
			return nil, fmt.Errorf("scanning sync run: %w", err)
		}
		runs = append(runs, &run)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating sync runs: %w", err)
	}

	return runs, nil
}

func normalizeCollectionLibraryIDs(legacyLibraryID int, libraryIDs []int) []int {
	if len(libraryIDs) == 0 && legacyLibraryID > 0 {
		libraryIDs = []int{legacyLibraryID}
	}
	if len(libraryIDs) == 0 {
		return nil
	}

	seen := make(map[int]struct{}, len(libraryIDs))
	normalized := make([]int, 0, len(libraryIDs))
	for _, id := range libraryIDs {
		if id <= 0 {
			continue
		}
		if _, ok := seen[id]; ok {
			continue
		}
		seen[id] = struct{}{}
		normalized = append(normalized, id)
	}
	return normalized
}

func groupKey(groupID *string) string {
	if groupID == nil {
		return ""
	}
	return *groupID
}

func compactCollectionMembershipOrder(ctx context.Context, tx pgx.Tx, libraryID int, groupID *string) error {
	_, err := tx.Exec(ctx, `
		WITH ranked AS (
		  SELECT collection_id,
		         ROW_NUMBER() OVER (ORDER BY sort_order ASC, collection_id ASC) - 1 AS pos
		  FROM library_collection_libraries
		  WHERE library_id = $1
		    AND group_id IS NOT DISTINCT FROM $2
		)
		UPDATE library_collection_libraries lcl
		SET sort_order = ranked.pos, updated_at = NOW()
		FROM ranked
		WHERE lcl.library_id = $1
		  AND lcl.collection_id = ranked.collection_id
		  AND lcl.group_id IS NOT DISTINCT FROM $2
	`, libraryID, groupID)
	if err != nil {
		return fmt.Errorf("compacting collection membership order: %w", err)
	}
	return nil
}

// ListDueForSync returns syncable collections whose next_sync_at is in the past.
// Note: in multi-node deployments, concurrent callers may receive overlapping
// sets. The in-memory inFlight guard in CollectionSyncScheduler prevents
// double-syncs within a single process.
func (r *LibraryCollectionRepository) ListDueForSync(ctx context.Context) ([]*models.LibraryCollection, error) {
	query := fmt.Sprintf(`
		SELECT %s
		FROM library_collections lc
		%s
		LEFT JOIN library_collection_items lci ON lci.collection_id = lc.id
		LEFT JOIN library_collection_libraries lcl ON lcl.collection_id = lc.id
		WHERE lc.sync_schedule IS NOT NULL
		  AND lc.next_sync_at IS NOT NULL
		  AND lc.next_sync_at <= NOW()
		  AND lc.collection_type IN ('mdblist', 'tmdb', 'trakt')
		GROUP BY lc.id, scope_lcl.group_id, scope_lcl.sort_order
		ORDER BY lc.next_sync_at ASC
	`, libraryCollectionColumns, libraryCollectionScopeFallbackJoin)

	rows, err := r.pool.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("listing due collections: %w", err)
	}
	defer rows.Close()

	return scanLibraryCollections(rows)
}

// UpdateNextSyncAt advances a collection's next scheduled sync time.
func (r *LibraryCollectionRepository) UpdateNextSyncAt(ctx context.Context, id string, next *time.Time) error {
	_, err := r.pool.Exec(ctx, `
		UPDATE library_collections
		SET next_sync_at = $2, updated_at = NOW()
		WHERE id = $1
	`, id, next)
	if err != nil {
		return fmt.Errorf("updating next sync at: %w", err)
	}
	return nil
}

func int32SliceToInts(values []int32) []int {
	if len(values) == 0 {
		return nil
	}
	result := make([]int, 0, len(values))
	for _, value := range values {
		result = append(result, int(value))
	}
	return result
}
